auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9100

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  chunk_idle_period: 5m
  chunk_retain_period: 30s

schema_config:
  configs:
    - from: 2024-10-25
      store: boltdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 168h

storage_config:
  boltdb:
    directory: C:/Users/murkt/PycharmProjects/standup_comedy_api/Loki/loki-data/index
  filesystem:
    directory: C:/Users/murkt/PycharmProjects/standup_comedy_api/Loki/loki-data/chunks

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  allow_structured_metadata: false

table_manager:
  retention_deletes_enabled: false
  retention_period: 0s