server:
  http_listen_port: 9080
  grpc_listen_port: 9096

positions:
  filename: C:/Users/murkt/PycharmProjects/standup_comedy_api/Loki/positions.yaml

clients:
  - url: http://127.0.0.1:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: standup_comedy_api
          __path__: C:/Users/murkt/PycharmProjects/standup_comedy_api/app.log
